export const SESSION_TIMEOUT_MINUTES = 10;
export const WARNING_BEFORE_LOGOUT_SECONDS = 60;

export const SESSION_TIMEOUT_MS = SESSION_TIMEOUT_MINUTES * 60 * 1000;
export const WARNING_BEFORE_LOGOUT_MS = WARNING_BEFORE_LOGOUT_SECONDS * 1000;
